spring:
 application:
  name: registry-server

eureka:
  environment: prod
  datacenter: none
  instance:
    hostname: registry-server
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8761/eureka/
