server:
  port: 8084

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
    register-with-eureka: false

spring:
  application:
    name: client-service

logging:
  file: logs/client-service.log
  level:
    com.example.howtodoinjava: DEBUG